

let trait = [

	"aggressive",
	"angry",
	"anxious",
	"apathetic",
	"arrogant",
	"athletic",
	"awkward",
	"beautiful",
	"brawny",
	"careless",
	"charming",
	"chubby",
	"clever",
	"clumsy",
	"confident",
	"cowardly",
	"curious",
	"deceptive",
	"diplomatic",
	"excited",
	"fat",
	"foolish",
	"funny",
	"graceful",
	"handsome",
	"happy",
	"hideous",
	"honest",
	"honorable",
	"hostile",
	"humble",
	"hyperactive",
	"inexperienced",
	"lazy",
	"mean",
	"muscular",
	"nice",
	"passionate",
	"peaceful",
	"polite",
	"poor",
	"proud",
	"rude",
	"sad",
	"sarcastic",
	"scared",
	"serious",
	"short",
	"skinny",
	"svelte",
	"tall",
	"thin",
	"trustworthy",
	"ugly",
	"wealthy",
	"wiry",
	"wily",
	"wise",
	"deranged",
	"selfish",
	"treasonous",
	"monstrous",
	"dishonest",
	"sexy", 
	"repulsive",
	"perverse",
	"hedonistic",
	"paranoid",
	"self-absorbed",
	"jealous",
	"ravenous",
	"scheming",
	"greedy",
	"vain",
	
	]

	let sect = [
	"Camarilla",
	"Anarch",
	"Sabbat",
	"Autarkis"
	]

	let playclan = [
	"Ventrue",
	"Toreador",
	"Tremere",
	"Gangrel",
	"Malkavian",
	"Brujah",
	"Nosferatu",
	"Hecata",
	"Lasombra",
	"Tzimisce",
	"Banu Haqim",
	"Ravnos",
	"Setite",
	"Giovanni",
	"Samedi",
	"Caitiff",
	"Duskborn",
	"Daughter of Cacophony",
	"Salubri",
	"Gargoyle",
	"Volgirre"
	]


	let pickedtrait1=trait[Math.floor(Math.random() * trait.length)]
	let pickedtrait2=trait[Math.floor(Math.random() * trait.length)]
	
	let pickedsect=sect[Math.floor(Math.random() * sect.length)]
	let pickedplayclan=playclan[Math.floor(Math.random() * playclan.length)]

	let vowelcheck = function(word) {
		let vowels = [ "a", "e", "i", "o", "u"]
		if (vowels.includes(word[0])) {
			return "An"
		} else {
			return "A" 
		}
	}


	let generate = () => {
		let pickedtrait1 = trait[Math.floor(Math.random() * trait.length)]
		let pickedtrait2 = trait[Math.floor(Math.random() * trait.length)]
		let pickedsect = sect[Math.floor(Math.random() * sect.length)]
		let pickedplayclan = playclan[Math.floor(Math.random() * playclan.length)]

		let description = document.querySelector('.character-description')
		description.classList.remove('hidden')
		description.textContent = vowelcheck(pickedtrait1) +" "+ pickedtrait1 + ", " + pickedtrait2 + " " + pickedsect + " " + pickedplayclan
	}

	const generator = document.querySelector("#generator"); 
generator.addEventListener("click", generate)

		
/*TODO:
Remove "hidden" class from character-description 
Change placeholder text to generate() output

*/













/* Template Literal structure

This vampire is a [num >3 && <=12] generation [age = Elder, Ancilla, Neonate or Fledgling] [clan] [pronoun] [is/are] [sect = Camarilla, Sabbat, or Anarch] 


This vampire is [a/an] [gen] generation [age] [clan]. [pronoun] [is/are] [a/an] [sect]. 


This vampire is an 11th generation Ancilla Malkavian. She is an Autarkis. 

Attributes: 

Mental: 
Perception 1 + 3 
Intelligence 1 + 1
Wits 1 + 1 

Social: 
Charisma 1 + 1 
Manipulation 1 + 1 
Appearance 1 + 2

Physical: 
Strength 1 + 2 
Dexterity 1 + 1
Stamina 1 + 2

Abilities: 

Talents:
Alertness 2 
Athletics 2 
Awareness 3
Brawl 1
Empathy 3
Streetwise 2

Skills: 
Craft 3 
Performance 2
Stealth 3
Survival 2 

Knowledges
Medicine 2
Occult 3

Disciplines:
Auspex 3
Obfuscate 




torDisciplines = [Auspex, Presence, Celerity]
ventDisciplines = [Dominate, 

*/

/* TODO: Stats

Part 1 : Attributes


	1. Take the numbers 7, 5 and 3 and place them in an array. 
		
		for a number of turns equal to the length of the list, iterating by 1: 
			-The .forEach() method can be used on the array. 
			-Choose a random number corresponding to an index from the list and assign it to the variable chosenNumber. 
			-Repeat with the remaining two numbers until only one remains. 
			-Assign each number to one of three variables: 
				mentalPoints 
				physicalPoints
				socialPoints
				-If a variable already has a value, skip over it. 
		
			
		
			
			const randomNumAssign = (arr) => {
				arr.forEach(num => {
				console.log("The list is " + arr) 
				const chosenNumber = arr[Math.floor(Math.random() * arr.length)] //Chooses 	the number by calling its index generated by math.random from the length of the array
				console.log(`${chosenNumber} was removed from the list`); //prints the chosen number
				arr.splice(arr.indexOf(chosenNumber), 1); //Takes out the chosen number from the array at its index.
				console.log("The list is now " + arr)//print the array for debugging purposes
					}
				)
			};
    
    
			
				
		

		let pointsArray = [7, 5, 3]


		/*1. Function takes an array as an argument. 
		  2. For a number of turns equal to the length of the array, function chooses a random index from the array and places it in a variable. 
		const randomNumAssign = (arr, varName) => {
		for(let	 ndx = 0; ndx < arr.length; ndx++) {
			const varName = arr[Math.floor(Math.random() * arr.length)]
			console.log(varName)
			console.log(arr)
			}
		};

		*/ 
		
/*let pointsArray = [7, 5, 3]

const randomNumAssign = (arr) => {
  for (let ndx = 0; ndx < arr.length; ndx++) 
  {
  console.log("The list is "+ arr)
    const chosenNumber = arr[Math.floor(Math.random() * arr.length)] //Chooses the number by calling its index generated by math.random from the length of the array
    console.log(`${chosenNumber} was removed from the list`) //prints the chosen number
    arr.splice(arr.indexOf(chosenNumber), 1) //Takes out the chosen number from the array at its index.
    console.log("The list is now " + arr)//print the array for debugging purposes
   }
};

randomNumAssign(pointsArray);


	1. Take the numbers 7, 5 and 3 and randomly assign them to Mental, Physical or Social
		
		let pointsArray = [7, 5, 3];	
		pointsArray[Math.floor(Math.random() * pointsArray.length)]
		
			Select a value and remove it from the list so it doesn't get assigned to any other value
			
		
		let mentalPoints = pointsArray[]
		let socialPoints = pointsArray[]
		let physicalPoints = pointsArray[]
		
	2. Randomly assign a number between 0 and 3 to each stat within each category, as long as the total number of points is less than the value assigned to that category. 1 to each random number.
	
		let stat = 1 + statvalue
		
		while statvalue < 3: 
		
		
		Create array from each category
		
		let mentalAttrs = ["Perception", "Intelligence", "Wits" 
	
		Mental Attributes:
			Perception
			Intelligence
			Wits
		
		Social Attributes:
			Charisma
			Manipulation
			Appearance
			
		Physical Attributes:
			Strength
			Dexterity
			Stamina
	
*/